on:
    push:
        branches:
            - master




jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3

         

          - name: "see the path "
            run: pwd 
          - name: "hashish "
            run: echo hashish 

          
